version: "3"

services:
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: postgres
        ports:
            - 5432:5432

    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
            PGADMIN_DEFAULT_PASSWORD: password
            PGADMIN_LISTEN_PORT: 80
        ports:
            - 81:80
        depends_on:
            - postgres
